#!/bin/bash

export DBUS_SESSION_BUS_ADDRESS="unix:path=/run/user/1000/bus"
export DISPLAY=":0"

if [[ $(xprop -id "$(xdotool getactivewindow)" | grep -c _NET_WM_STATE_FULLSCREEN) -gt 0 ]]; then
   zenity --warning --no-wrap --no-markup --title "$2" --text "$3" &
   sleep 1
   xdotool windowstate --add ABOVE "$(xdotool search --pid $! | tail -n 1)"
else
   notify-send -u critical "$2" "$3 https://live.bilibili.com/$4"
fi
